- name: cart service
  hosts: all
  become: true
  tasks:
    - name: copy cart service local to remote
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: Install nodejs package
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: Create a user
      ansible.builtin.user:
        name: roboshop

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: make a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download cart
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: Extract cart
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: Install npm
      community.general.npm:
        name: npm
        path: /app
