- name: mysql db
  hosts: all
  become: true
  tasks:
    - name: Install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: credentials setup
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

    - name: start mysqld service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: true