- name: redis cache memory
  hosts: all
  become: true
  tasks:
   - name: Install redis package
     ansible.builtin.dnf:
       name: '@redis:7'
       state: present

   - name: Replace old text with new text
     ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: 'protected-mode yes'
       replace: 'protected-mode no'

   - name: Replace old bind address with new address
     ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: '^#bind 127.0.0.1'
       replace: '#bind 0.0.0.0'

   - name: start redis service
     ansible.builtin.systemd_service:
       name: redis
       state: started
       enabled: true