- name: shipping service
  hosts: all
  become: true
  tasks:
    - name: copy shipping service local to remote
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Install maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: Create a user
      ansible.builtin.user:
        name: roboshop

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: make a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download shipping
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: Extract shipping
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: mvn clean package
      ansible.builtin.shell: mvn clean package
      args:
        chdir: /app

    - name: move
      ansible.builtin.shell: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: load schema
      community.mysql.mysql_db:
        login_user: root
        login_password: RoboShop@1
        login_host: mysql-dev.pdevops87.online
        login_port: 3306
        name: all
        target: /app/db/schema.sql
        state: present


